version: "3"
services:
  nginx:
    container_name: my-nginx-container
    image: nginx:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

